### ISSUE TITLE
facts cannot be cased as described

### ISSUE THREAD

**Issue by towo** [mcanevet/rspec-puppet-facts#85]
When trying to use a `case facts[:osfamily]` like described, I'm getting the following error trying to do a validation:

```
An error occurred while loading ./spec/classes/libvirt_spec.rb.
Failure/Error: case facts[:osfamily]
  `facts` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc).
# ./spec/classes/libvirt_spec.rb:11:in `block (3 levels) in <top (required)>'
# ./spec/classes/libvirt_spec.rb:7:in `block (2 levels) in <top (required)>'
# ./spec/classes/libvirt_spec.rb:6:in `each'
# ./spec/classes/libvirt_spec.rb:6:in `block in <top (required)>'
# ./spec/classes/libvirt_spec.rb:5:in `<top (required)>'
Run options: exclude {:bolt=>true}
```

Where I'm literally just proceeding as exampled:

```
describe 'libvirt', type: :class do
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) do
        os_facts
      end
      case facts[:osfamily]
      when 'Debian'
        let :params do
          {
            package_libvirtd: 'libvirtd',
            package_libvirt_devel: 'libvirt-dev'
          }
        end
        it {
          is_expected.to contain_package('libvirtd').with(
            'ensure' => 'present',
          )
        }
        it {
          is_expected.to contain_package('libvirt-dev').with(
            'ensure' => 'present',
          )
        }
        it {
          is_expected.to contain_package('ruby-libvirt').with(
            'ensure' => 'present',
            'provider' => 'puppet_gem',
          )
        }
      end
      it { is_expected.to compile }
    end
  end
end
```

So the documentation would clearly need some form of update as to how to do a OS-specific distinction here.

**Comment by ghoneycutt** [comment]
Thanks for reporting this! Could you send us a PR to fix the docs?

**Comment by towo** [comment]
Hah, you assume I've found a solution yet. :slightly_frowning_face:

**Comment by nabertrand** [comment]
You would need to use `os_facts[:osfamily]` instead of `facts[:osfamily]` since that's what you've called the facts variable in `on_supported_os.each do |os, os_facts|`. Notice that the example actually calls the facts variable `facts`, not `os_facts`:
```ruby
  on_supported_os.each do |os, facts|
    context "on #{os}" do
...
      # If you need to specify any operating system specific tests
      case facts[:osfamily]
```
Also note that `let` definitions are only available within an example, e.g. `it { ... }` and not example groups, e.g. `context ...`. So `facts[:osfamily]` would work for you within an `it` block, but not within a `context` block.

I have run into this confusion myself as the Puppet Development Kit spec templates use `os_facts` while the examples in this documentation use `facts`, e.g. https://github.com/puppetlabs/pdk-templates/blob/2b3320584b8d6ceb9027b441582bb4e16c3d6350/object_templates/class_spec.erb#L4 and https://github.com/puppetlabs/pdk-templates/blob/2b3320584b8d6ceb9027b441582bb4e16c3d6350/object_templates/defined_type_spec.erb#L9. Would it make sense to update this documentation to match the PDK templates?

**Comment by ghoneycutt** [comment]
Perhaps it would be better to update PDK's templates to use `facts` as that makes more sense than their implementation using `os_facts`

**Comment by rodjek** [comment]
No, in this case it's the rspec-puppet-facts documentation that is wrong. The `facts` local variable is actually a memoised helper expected to be created by `let(:facts)` as standard practice in rspec-puppet. The docs for rspec-puppet-facts set up a rather confusing situation where one of the `facts` values ends up shadowed, which while it technically works it should not be encouraged.

```ruby
on_supported_os.each do |os, facts| # <-- facts hash added to scope
  let(:facts) do # <-- facts hash now shadowed by the memoised facts helper
    facts # <-- Want to guess what this value will be at a specific time of evaluation?
  end
```

**Comment by ghoneycutt** [comment]
@rodjek you seem to know what's going on with this, could you send a PR to the docs?

**Comment by threepistons** [comment]
@towo https://github.com/rodjek/rspec-puppet/issues/774#issuecomment-549850505 describes correct syntax.
