### ISSUE TITLE
Commit 21442e7 looks to introduce hard to debug behavior

### ISSUE THREAD

**Issue by Dan33l** [mcanevet/rspec-puppet-facts#97]
In the module [voxpupuli/puppet-snmp](https://github.com/voxpupuli/puppet-snmp). Tests that previously was passing (with rspec-puppet-facts version 1.9.2), without modification are now failing (with rspec-puppet-facts version 1.9.5).

You can find details about my debug work in issue https://github.com/voxpupuli/puppet-snmp/issues/199.

A more explicit message would really be useful, or it is a bug introduced by https://github.com/mcanevet/rspec-puppet-facts/commit/21442e77a1ef21bc3e60b45a2eee66cc92c7df4c

**Comment by ghoneycutt** [comment]
@Dan33l could you please link to the failing travis run

**Comment by Dan33l** [comment]
My debug issue have the PR that failed. But here the link to travis:
https://travis-ci.org/voxpupuli/puppet-snmp/jobs/566740301

**Comment by Dan33l** [comment]
Perhaps display in message the missing fact ?

**Comment by ekohl** [comment]
I also believe the behavior introduced in https://github.com/mcanevet/rspec-puppet-facts/commit/21442e77a1ef21bc3e60b45a2eee66cc92c7df4c was incorrect since its fallback became unreliable. In https://github.com/mcanevet/rspec-puppet-facts/commit/5001d51838b884c6737c2b890d3e206bc9dfa36e I've addressed this and also made it much faster.

> Perhaps display in message the missing fact ?

https://github.com/mcanevet/rspec-puppet-facts/pull/115 improves logging.

**Comment by ghoneycutt** [comment]
Closing as @ekohl addressed this with the improved logging.
